stages:
  - test-latest
  - test-all
  - deploy

test_latest:
  stage: test-latest
  image: python:latest
  before_script:
    - pip install .
  script:
    - python -m unittest --verbose graphdb

test_alpine:
  stage: test-all
  image: python:alpine
  before_script:
    - pip install .
  script:
    - python -m unittest --verbose graphdb

test_3.7:
  stage: test-all
  image: python:3.7
  before_script:
    - pip install .
  script:
    - python -m unittest --verbose graphdb

test_3.6:
  stage: test-all
  image: python:3.6
  before_script:
    - pip install .
  script:
    - python -m unittest --verbose graphdb

test_3.5:
  stage: test-all
  image: python:3.5
  before_script:
    - pip install .
  script:
    - python -m unittest --verbose graphdb

deploy_job:
  stage: deploy
  image: docker:dind
  script:
    - pwd
    - ls -lthar